### PR TITLE
Feature/adapt to rollups 1.2.0

### PR DESCRIPTION
**Pull request by endersonmaia**
TODO:

- [x] stop using volume for `/deployments/$network/dapp.json` with `--dapp-deployment-file` and get `values.yaml` using specific parameters;
- [x] stop using volume for `/opt/cartesi/share/deployments/$network.json` and `--rollups-deployment-file`  and get from `values.yaml` using specific parameters;
~~- [ ] clean redis streams by default using an entrypoint for rollups-dispatcher container~~

### CODE REVIEW

**Comment by oap75** [comment]
When I want to deploy the chart in sepolia the dispatcher and authority server crashed. 

```
Error: BlockchainError { source: JsonReadError { path: "/opt/cartesi/share/deployments/sepolia.json", source: Error("missing field `History`", line: 1200, column: 3) } }

```

**Review by oap75 — CHANGES_REQUESTED** [review]
When I want to deploy the chart in sepolia the dispatcher and authority server crashed.

```
Error: BlockchainError { source: JsonReadError { path: "/opt/cartesi/share/deployments/sepolia.json", source: Error("missing field `History`", line: 1200, column: 3) } }
```

**Review by oap75 — APPROVED** [review]

**Review by oap75 — APPROVED** [review]
Let's just update the Readme

**Comment by endersonmaia** [comment]
> Let's just update the Readme

Can you send a PR?

**Pull request merged**
